export const TEXTS_EN = {
    common: {
        confirm: 'Confirm',
        cancel: 'Cancel',
        updateTitle: 'Update Available',
        updateMessage: 'A new version of the app is available. Please update to the latest version.',
        updateNow: 'Update Now',
        updateLater: 'Later',
        home: 'Home',
        records: 'Records',
    },
    appName: 'Daily Sudoku',
    daily: {
        title: 'Daily Sudoku',
        subtitle: 'Play a new puzzle every day!',
        playButton: 'Play Today\'s Puzzle',
        startAlertTitle: 'Start Daily Challenge?',
        startAlertMessage: 'This will abandon your current daily challenge progress. Do you want to start a new one?',
        startAlertCancel: 'Cancel',
        startAlertStart: 'Start',
        rankTabs: {
            today: 'Today',
            streak: 'Streak',
        },
    },
    tabs: {
        daily: 'Daily',
        home: 'Home',
        records: 'Records',
    },
    home: {
        newGame: 'New Game',
        continue: 'Resume',
        stats: 'Stats',
        settings: 'Settings',
        newGameAlertTitle: 'New Game',
        newGameAlertMessage: 'You have a saved game. Starting a new game will overwrite it. Do you want to continue?',
    },
    game: {
        difficulty: {
            beginner: 'Beginner',
            easy: 'Easy',
            medium: 'Medium',
            hard: 'Hard',
            expert: 'Expert',
            daily: 'Daily',
        },
        lockMessage: {
            easy: 'Win 3 Beginner games to unlock',
            medium: 'Win 5 Easy games to unlock',
            hard: 'Win 7 Medium games to unlock',
            expert: 'Win 10 Hard games to unlock',
            unlockCondition: (difficulty: string, remaining: number) => `Win ${remaining} more ${difficulty} game${remaining > 1 ? 's' : ''} to unlock`,
        },
        overlayTitle: {
            pause: 'Pause',
            loss: 'Game Over',
            success: 'Success',
        },
        overlayButtons: {
            continue: 'Continue',
            restart: 'Restart',
            newGame: 'New Game',
            home: 'Home',
        },
        mistakeCounter: (mistakes: number, limit: number) => `Mistakes ${mistakes}/${limit}`,
        actions: {
            undo: 'Undo',
            erase: 'Erase',
            hint: 'Hint',
            note: 'Note',
            padMode: 'Pad Mode',
            aiHint: 'AI Hint',
        },
    },
    stats: {
        title: 'My Statistics',
        tabs: {
            statistics: 'Statistics',
            rankings: 'Rankings',
        },
        summary: {
            gamesPlayed: 'Games Played',
            winRate: 'Win Rate',
            winStreak: 'Win Streak',
            avgTime: 'Avg. Time',
        },
        ratio: {
            title: 'Win / Loss Ratio',
            winsLabel: 'Wins',
            lossesLabel: 'Losses',
        },
        completed: {
            title: 'Completed Games',
            subtitle: 'All Time',
        },
        bestTimes: {
            title: 'Best Times',
            beginner: 'Beginner',
            easy: 'Easy',
            medium: 'Medium',
            hard: 'Hard',
            expert: 'Expert',
        },
        rankings: {
            title: 'Leaderboard',
            rank: 'Rank',
            user: 'User',
            score: 'Score',
            noData: 'No ranking data available.',
            metric: {
                bestTime: 'Best Time',
                winRate: 'Win Rate',
                wins: 'Wins',
            },
        },
        reset: {
            title: 'Reset Records',
            selectAll: 'Select All',
            warningTitle: 'Warning',
            warningMessage: 'Are you sure you want to reset the selected records? This action cannot be undone.',
            success: 'Records reset successfully.',
            button: 'Reset',
        },
    },
    settings: {
        title: 'Settings',
        language: 'Language',
        account: 'Account Info',
        userId: 'User ID',
        type: 'Type',
        guest: 'Guest (Anonymous)',
        google: 'Google Account',
        linkGoogle: 'Link your account to Google to save your progress across devices.',
        signOut: 'Sign Out',
        success: 'Success',
        linked: 'Account linked successfully!',
        loginFailed: 'Login Failed',
        loginFailedMsg: 'Could not sign in with Google.',
        loggedOut: 'Logged Out',
        loggedOutMsg: 'You have been successfully signed out. The app will now close.',
        error: 'Error',
        signOutFailed: 'Failed to sign out.',
        bgm: 'Background Music',
        sfx: 'Sound Effects',
    },
    tutorial: {
        step1: {
            title: 'Goal',
            text: 'Sudoku is a puzzle where you fill a 9x9 grid with numbers.\nEach cell contains a number from 1 to 9.',
        },
        step2: {
            title: 'Row Rule',
            text: 'Each row must contain the numbers 1 to 9,\nwithout repetitions.\n\nTap an empty cell to fill it.',
        },
        step3: {
            title: 'Column Rule',
            text: 'Each column must also contain the numbers 1 to 9,\nwithout repetitions.',
        },
        step4: {
            title: 'Box Rule',
            text: 'Each 3x3 box outlined in bold must contain\nthe numbers 1 to 9 without repetitions.',
        },
        step5: {
            title: 'Basic Strategy',
            text: 'This is the most important strategy!\nCheck the numbers already in rows, columns, and boxes\nto find the only possible number for an empty cell.',
        },
        step6: {
            title: 'Controls & Notes',
            text: 'Tap the number pad to input numbers.\nTap the note icon to toggle Note Mode,\nallowing you to write small candidate numbers.',
        },
        step7: {
            title: 'Mistakes',
            text: 'Entering a wrong number counts as a mistake.\n3 mistakes will end the game!\n(But it\'s okay in this tutorial)',
        },
        step8: {
            title: 'Practice 1',
            text: 'Look at the second row. The number 7 is missing.\nSelect the empty cell and enter 7.',
        },
        step9: {
            title: 'Practice 2',
            text: 'Look at the last empty cell in the first row.\nThe number 1 is missing.\nEnter 1 to complete the row.',
        },
        step10: {
            title: 'Start Game',
            text: 'The tutorial is complete!\nNow fill in all the remaining empty cells.\nGood luck!',
        },
        buttons: {
            prev: 'Prev',
            next: 'Next',
            complete: 'Complete',
        },
    },
};

export type TextResources = typeof TEXTS_EN;
